package com.eohi.hx.ui.work.model

data class CommonPostModel(
    var WPH: String,
    var GG: String,
    var WPMC: String,
    var JYJG: String,
    var HGSL: String,
    var JSSL: String,
    var BHGSL: String,
    var SQMS: String,
    var JYYID: String,
    var JYSJ: String,
    var ZJRWDH: String,
    var GSH: String,
    var GDH: String,
    var CX: String,
    var CXID: String,
    var JYGX: String,
    var GXH: String,
    var JYSL: String,
    var JYMS: String,
    var TMH: String,
    var DJH: String,
    var TPWJM: String,
    var CGDDH: String,
    var JYDH: String,
    var JYLXM: String,//检验类型
    var DATA: ArrayList<BtBean>,
    var BLYY: ArrayList<BlxxBean>
) {
    constructor() : this(
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ArrayList(),
        ArrayList()
    )
}
