package com.eohi.hx.ui.work.model

/**
 * @author zhaoli.Wang
 * @description:
 * @date :2021/7/6 14:08
 */
data class ProductionProcessesModel(
    val BGRID: Any,
    val BGRXM: Any,
    val BGSJ: Any,
    val BGSL: Any,
    val BGWC: Any,
    val BLSL: Any,
    val BZS1: Double,
    val CJBH1: String,
    val DQBZNSL: Double,
    val DQGX: String,
    val DQGXLJBGSL: Any,
    val DQWZ: Any,
    val DjBth: Int,
    val DjGuid: String,
    val DjLsh: Int,
    val DjState: Any,
    val GCBH1: String,
    val GSH1: String,
    val GXFDBH: Int,
    val GXH: String,
    val GXMS: String,
    val GXMS1: Any,
    val HGSL: Any,
    val KGR: Any,
    val KGRID: Any,
    val KGSJ: Any,
    val KGWC: Any,
    val RK: Any,
    val RWDH1: String,
    val SCFS: Any,
    val SCRID: Any,
    val SCRXM: Any,
    val SCSL1: Double,
    val SFBGD: String,
    val SFZJD: Any,
    val TBZS: Any,
    val THH: Int,
    val TLZKKH: String,
    val TXH: Int,
    val WPH1: String,
    val WX: Any,
    val YLZD1: Any,
    val YLZD2: Any,
    val YLZD3: Any,
    val YLZD4: Any,
    val YLZD5: Any,
    val YLZD6: Any,
    val ZXBGSBBH: Any,
    val ZXBGSBMC: Any,
    val ZYQD: Any
)