package com.eohi.hx.ui.work.model

/**
 * @author zhaoli.Wang
 * @description:
 * @date :2021/7/6 13:32
 */
data class TransferCardInfoModel(
    val bz: String,
    val bzs: Int,
    val bzsysl: Any,
    val cjbh: String,
    val cjdd: Any,
    val cjddck: Any,
    val cjmc: String,
    val cjrq: String,
    val cjyh: String,
    val cjyhid: String,
    val ddgbrq: Any,
    val dqrq: Any,
    val dybz: Any,
    val dycs: Any,
    val dyrid: Any,
    val dyrq: Any,
    val dyrxm: Any,
    val gbbz: String,
    val gbr: Any,
    val gbrid: Any,
    val gcbh: String,
    val gcmc: String,
    val gg: String,
    val gsh: String,
    val gsmc: String,
    val gxzzm: String,
    val gyfams: String,
    val hkyssl: Any,
    val jhwcrq: String,
    val jldw: String,
    val khddh: Any,
    val khddhh: Any,
    val khh: Any,
    val khmc: Any,
    val ly: String,
    val lydh: Any,
    val lzkkh: String,
    val lzklx: String,
    val lzkrq: String,
    val lzkzt: String,
    val rksj: Any,
    val rwdh: String,
    val rwdzt: String,
    val rwlx: String,
    val rwrq: String,
    val scsl: Int,
    val sybzs: Int,
    val th: String,
    val wcsl: Any,
    val whrq: String,
    val whyh: String,
    val whyhid: String,
    val wpfl: String,
    val wph: String,
    val wpmc: String,
    val xsddh: Any,
    val xsddhh: Any,
    val yqjhq: Any,
    val zdsc: String,
    val zxbggx: Any,
    val zxbgrq: Any,
    val zxbgsl: Any
)