package com.eohi.hx.ui.work.equipment.model

data class Fault(
    val BJEWM: String,
    val CSH: String,
    val CSMC: String,
    val FSGZSJ: String,
    val GSH: String,
    val GSMC: String,
    val GZBM: String,
    val GZMC: String,
    val GZQK: String,
    val GZQRMS: Any,
    val GZTP: String,
    val JJCD: String,
    val PJSWH: String,
    val QRSJ: Any,
    val QRYH: Any,
    val QRYHH: Any,
    val SBBH: String,
    val SBBJBH: String,
    val SBBJMC: String,
    val SBDQSZWZ: String,
    val SBMC: String,
    val SBSZQYBH: String,
    val SBSZQYMC: String,
    val SBSZWZBH: String,
    val SBSZWZMC: String,
    val SFGZ: Any,
    val SFYJQR: String,
    val SMSJ: String,
    val SMYH: String,
    val SMYHH: String,
    val WBGZBH: Any,
    val WBGZMC: Any,
    val WXZT: Any,
    val XDWCGS: Int,
    val XH: String,
    val ZDQRYHH: String,
    val ZDQRYHM: String,
    val ZT: String

)